
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    - name: Install Playwright browsers
      run: uv run playwright install --with-deps
    - name: Run tests
      run: uv run pytest
